name: Premarket-5 Light
on:
  schedule:
    - cron: '40 7 * * 1-5'   # EDT(UTC-4) 07:40 = 03:40 ET
    - cron: '40 8 * * 1-5'   # EST(UTC-5) 08:40 = 03:40 ET(겨울)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        run: python main_light.py
