name: Premarket-5 Pro (DDM)
on:
  schedule:
    # 03:40 ET (DST=07:40 UTC / STD=08:40 UTC)
    - cron: '40 7 * * 1-5'
    - cron: '40 8 * * 1-5'
    # 04:10 ET (DST=08:10 / STD=09:10)
    - cron: '10 8 * * 1-5'
    - cron: '10 9 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - env:
          POLYGON_API_KEY:   ${{ secrets.POLYGON_API_KEY }}
          BENZINGA_API_KEY:  ${{ secrets.BENZINGA_API_KEY }}
          FINNHUB_API_KEY:   ${{ secrets.FINNHUB_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main_light.py   # ← 파일명 맞춰줌
